# debian:trixie
#   https://hub.docker.com/_/gcc

ARG COMPILER_VERSION=16
FROM gcc:${COMPILER_VERSION} AS dependencies

ARG USE_SANITIZERS=OFF
ARG BUILD_TYPE=Debug
ARG DEBIAN_FRONTEND=noninteractive

# note: gumbo submodule depends on autotools
RUN apt-get update -y \
    && apt-get install -y --no-install-recommends \
       lsb-release wget curl gnupg git ca-certificates \
       autoconf automake libtool m4 \
       make cmake ninja-build \
       libboost-filesystem-dev libboost-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

FROM dependencies AS build
WORKDIR /pisa
COPY . .

RUN cmake -B build \
    -G Ninja \
    "-DCMAKE_BUILD_TYPE=${BUILD_TYPE}" \
    -DPISA_BUILD_TOOLS='OFF' \
    -DPISA_ENABLE_BENCHMARKING='OFF' \
    -DPISA_SYSTEM_BOOST='ON' \
    "-DPISA_SANITIZERS=${USE_SANITIZERS}" \
    && cmake --build build --config "${BUILD_TYPE}" -j $(nproc)

WORKDIR /pisa/build
CMD ["ctest", "-VV", "-j", "4"]
