name: Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: true
      matrix:
        compiler: [gcc]
        version: [16]
        include:
          - compiler: llvm
            version: 23

    steps:
      - name: Clone repo
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Build
        shell: bash
        run: |
          IMAGE_NAME="pisa-ci:${{ matrix.compiler }}-${{ matrix.version }}"
          DOCKER_FILE="${{runner.workspace}}/pisa/test/docker/Dockerfile.${{ matrix.compiler }}"

          docker build \
            -f $DOCKER_FILE \
            --build-arg COMPILER_VERSION=${{ matrix.version }} \
            --build-arg BUILD_TYPE=Debug \
            --build-arg USE_SANITIZERS=OFF \
            -t $IMAGE_NAME .

      - name: Run
        shell: bash
        run: |
          IMAGE_NAME="pisa-ci:${{ matrix.compiler }}-${{ matrix.version }}"
          docker run --rm $IMAGE_NAME
